### ISSUE TITLE
Is there any paper about this repository?

### ISSUE THREAD

**Issue by GhostSteven** [swpenninga/permeabilityCNN#1]
Nice works! Our team are really interested in your program, but we meet some difficulties while learning and using your codes. Could you tell us if  there is any paper or related reference published about this repository? We really need it to help us understand the details of your codes.  Thank you very much.

**Comment by swpenninga** [comment]
[permeabilityCNN.pdf](https://github.com/swpenninga/permeabilityCNN/files/6435226/permeabilityCNN.pdf)

Hi Steven, nice to see that you're interested. I have indeed written a paper about this repository, I suppose it does not make much sense without it.

**Comment by GhostSteven** [comment]
> [permeabilityCNN.pdf](https://github.com/swpenninga/permeabilityCNN/files/6435226/permeabilityCNN.pdf)
> 
> Hi Steven, nice to see that you're interested. I have indeed written a paper about this repository, I suppose it does not make much sense without it.

Glad to see your reply! So could you please provide the paper **_doi_** for us _lol_. I have searched it for times but failed. Thank you very much!

**Comment by GhostSteven** [comment]
> [permeabilityCNN.pdf](https://github.com/swpenninga/permeabilityCNN/files/6435226/permeabilityCNN.pdf)
> 
> Hi Steven, nice to see that you're interested. I have indeed written a paper about this repository, I suppose it does not make much sense without it.

I have seen the new file that you uploaded, thank you very much!
